Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1491,6 +1491,21 @@ exit 0' >$RCLOCAL
 		clear
 		echo -e "\E[44;1;37m            GERENCIAR PROXY SOCKS             \E[0m"
 		echo ""
+
+                [[ $(netstat -nplt | grep -wc 'security') != '0' ]] && {
+                   porta_security=$(netstat -nplt | grep -w 'security' | awk '{split($4,a,":"); print a[length(a)]}')
+                  sks='\033[1;32mON'
+                  echo -e "\033[1;32mPORTAS (security)\033[1;31m: \033[1;37m$porta_security"
+    }
+    
+              [[ $(netstat -nplt | grep -wc 'proxydt') != '0' ]] && {
+                porta_proxydt=$(netstat -nplt | grep -w 'proxydt' | awk '{split($4,a,":"); print a[length(a)]}')
+          sks='\033[1;32mON'
+           echo -e "\033[1;32mPORTAS (proxydt)\033[1;31m: \033[1;37m$porta_proxydt"
+    }
+
+
+
 		[[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
 			sks='\033[1;32mON'
 			echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
@@ -1498,11 +1513,13 @@ exit 0' >$RCLOCAL
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m◉" || var_sks1="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
+                [[ $(screen -list | grep -wc 'proxydt') != '0' ]] && var_sks8="\033[1;32m◉" || var_sks8="\033[1;31m○"
                 [[ $(screen -list | grep -wc 'novoWS') != '0' ]] && var_sks3="\033[1;32m◉" || var_sks3="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m◉" || sksop="\033[1;31m○"
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $var_sks1 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
+                echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mDTPROXY $var_sks8 \033[0m"
                 echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET SECURITY$var_sks3 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
@@ -1693,7 +1710,74 @@ exit 0' >$RCLOCAL
 
 
 
+
+
+
+
+
+                elif [[ "$resposta" = '8' ]]; then
+    clear
+    if ps x | grep -w proxydt | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\E[41;1;37m             PROXY DT               \E[0m"
+        echo ""
+        fun_proxydtoff() {
+            for pidproxy in $(screen -ls | grep ".proxydt" | awk {'print $1'}); do
+                screen -r -S "$pidproxy" -X quit
+            done
+            [[ $(grep -wc "proxydt" /etc/autostart) != '0' ]] && {
+                sed -i '/proxydt/d' /etc/autostart
+            }
+            sleep 1
+            screen -wipe >/dev/null
+        }
+        echo -e "\033[1;32mDESATIVANDO O PROXY DT\033[1;33m"
+        echo ""
+        fun_bar 'fun_proxydtoff'
+        echo ""
+        echo -e "\033[1;32mPROXY DT DESATIVADO COM SUCESSO!\033[1;33m"
+        
+        fun_socks
+    else
+        echo -e "\E[44;1;37m             PROXY DT               \E[0m"
+        echo ""
+        echo -e "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033"
+        echo ""
+        echo -e "\033[1;32mEXEMPLO :\033[1;33m80 ou 8080\033"
+        echo ""
+        read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m: ")" porta
+        [[ -z "$porta" ]] && {
+            echo ""
+            echo -e "\033[1;31mPorta invalida!"
             
+            fun_socks
+        }
+        verif_ptrs $porta
+        fun_iniproxydt() {
+            sleep 1
+            screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXYDT
+            [[ $(grep -wc "proxydt" /etc/autostart) = '0' ]] && {
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXY; }" >>/etc/autostart
+            } || {
+                sed -i '/proxydt/d' /etc/autostart
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXY; }" >>/etc/autostart
+            }
+        }
+        echo ""
+        echo -e "\033[1;32mINICIANDO O PROXY DT\033[1;33m"
+        echo ""
+        fun_bar 'fun_iniproxydt'
+        echo ""
+        echo -e "\033[1;32PROXY DT ATIVADO COM SUCESSO\033[1;33m"
+        
+        fun_socks
+    fi
+
+
+
+
+
+
+
 
 
 
@@ -2168,6 +2252,25 @@ exit 0' >$RCLOCAL
 			} || {
 				sts4="\033[1;31m○ "
 			}
+
+
+
+[[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mPROXY DT\033[1;31m: \033[1;37m$(netstat -nplt | grep 'proxydt' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts8="\033[1;32m◉ "
+			} || {
+				sts8="\033[1;31m○ "
+			}
+
+			[[ "$(netstat -tlpn | grep -E 'python|proxydt|security' | wc -l)" != '0' ]] && {
+    echo -e "\033[1;32mPROXY SOCKS PORTAS ATIVADAS\033[1;31m: \033[1;37m$(netstat -nplt | grep -E 'python|proxydt|security' | awk '{print $4}' | cut -d: -f2 | xargs)"
+    sts8="\033[1;32m◉ "
+} || {
+    sts8="\033[1;31m○ "
+}
+
+
+                            
 
 			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mSSL TUNNEL \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
